### ISSUE TITLE
For rasa twilio connection, 405 method not found error

### ISSUE THREAD

**Issue by charanr0121** [bespoken/voice-helpdesk-assistant#3]
https://blog.rasa.com/twilio-voice-rasa-tutorial/

Following this tutorial, I came across an error that whenever I called the twilio number, I would get a 405 method not found error. I solved this problem by making the following changes to this repo.

**credentials.yml**
```
rest:

channels.twilio_voice.TwilioInput:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  twilio_number: <number_here>
```

**webhook endpoint**
opening up port 5005 with ngrok, copy the url and add the following end point to your twilio _A CALL COMES IN_ webhook
`/webhooks/twilio_voice/webhook`

should work with no issues!
